from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from trolie-flask.models.base_model import Model
from trolie-flask.models.forecast_limit_item_detailed import ForecastLimitItemDetailed
from trolie-flask.models.forecast_snapshot_header import ForecastSnapshotHeader
from trolie-flask import util

from trolie-flask.models.forecast_limit_item_detailed import ForecastLimitItemDetailed  # noqa: E501
from trolie-flask.models.forecast_snapshot_header import ForecastSnapshotHeader  # noqa: E501

class ForecastLimitsDetailedSnapshot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, snapshot_header=None, limits=None):  # noqa: E501
        """ForecastLimitsDetailedSnapshot - a model defined in OpenAPI

        :param snapshot_header: The snapshot_header of this ForecastLimitsDetailedSnapshot.  # noqa: E501
        :type snapshot_header: ForecastSnapshotHeader
        :param limits: The limits of this ForecastLimitsDetailedSnapshot.  # noqa: E501
        :type limits: List[ForecastLimitItemDetailed]
        """
        self.openapi_types = {
            'snapshot_header': ForecastSnapshotHeader,
            'limits': List[ForecastLimitItemDetailed]
        }

        self.attribute_map = {
            'snapshot_header': 'snapshot-header',
            'limits': 'limits'
        }

        self._snapshot_header = snapshot_header
        self._limits = limits

    @classmethod
    def from_dict(cls, dikt) -> 'ForecastLimitsDetailedSnapshot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The forecast-limits-detailed-snapshot of this ForecastLimitsDetailedSnapshot.  # noqa: E501
        :rtype: ForecastLimitsDetailedSnapshot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def snapshot_header(self) -> ForecastSnapshotHeader:
        """Gets the snapshot_header of this ForecastLimitsDetailedSnapshot.


        :return: The snapshot_header of this ForecastLimitsDetailedSnapshot.
        :rtype: ForecastSnapshotHeader
        """
        return self._snapshot_header

    @snapshot_header.setter
    def snapshot_header(self, snapshot_header: ForecastSnapshotHeader):
        """Sets the snapshot_header of this ForecastLimitsDetailedSnapshot.


        :param snapshot_header: The snapshot_header of this ForecastLimitsDetailedSnapshot.
        :type snapshot_header: ForecastSnapshotHeader
        """

        self._snapshot_header = snapshot_header

    @property
    def limits(self) -> List[ForecastLimitItemDetailed]:
        """Gets the limits of this ForecastLimitsDetailedSnapshot.

        Forecast including provenance information.  # noqa: E501

        :return: The limits of this ForecastLimitsDetailedSnapshot.
        :rtype: List[ForecastLimitItemDetailed]
        """
        return self._limits

    @limits.setter
    def limits(self, limits: List[ForecastLimitItemDetailed]):
        """Sets the limits of this ForecastLimitsDetailedSnapshot.

        Forecast including provenance information.  # noqa: E501

        :param limits: The limits of this ForecastLimitsDetailedSnapshot.
        :type limits: List[ForecastLimitItemDetailed]
        """
        if limits is not None and len(limits) > 50000:
            raise ValueError("Invalid value for `limits`, number of items must be less than or equal to `50000`")  # noqa: E501
        if limits is not None and len(limits) < 0:
            raise ValueError("Invalid value for `limits`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._limits = limits
