from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from trolie-flask.models.base_model import Model
import re
from trolie-flask import util

import re  # noqa: E501

class MutableRatingProposal(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, last_updated=None, ratings_provider=None):  # noqa: E501
        """MutableRatingProposal - a model defined in OpenAPI

        :param last_updated: The last_updated of this MutableRatingProposal.  # noqa: E501
        :type last_updated: datetime
        :param ratings_provider: The ratings_provider of this MutableRatingProposal.  # noqa: E501
        :type ratings_provider: str
        """
        self.openapi_types = {
            'last_updated': datetime,
            'ratings_provider': str
        }

        self.attribute_map = {
            'last_updated': 'last-updated',
            'ratings_provider': 'ratings-provider'
        }

        self._last_updated = last_updated
        self._ratings_provider = ratings_provider

    @classmethod
    def from_dict(cls, dikt) -> 'MutableRatingProposal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The mutable-rating-proposal of this MutableRatingProposal.  # noqa: E501
        :rtype: MutableRatingProposal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def last_updated(self) -> datetime:
        """Gets the last_updated of this MutableRatingProposal.

        RFC 3339 date-time string with a maximum of 10 digits in the fractional seconds component, i.e., nanosecond precision.  # noqa: E501

        :return: The last_updated of this MutableRatingProposal.
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: datetime):
        """Sets the last_updated of this MutableRatingProposal.

        RFC 3339 date-time string with a maximum of 10 digits in the fractional seconds component, i.e., nanosecond precision.  # noqa: E501

        :param last_updated: The last_updated of this MutableRatingProposal.
        :type last_updated: datetime
        """
        if last_updated is not None and len(last_updated) > 35:
            raise ValueError("Invalid value for `last_updated`, length must be less than or equal to `35`")  # noqa: E501

        self._last_updated = last_updated

    @property
    def ratings_provider(self) -> str:
        """Gets the ratings_provider of this MutableRatingProposal.

        Usually the NERC id of the entity.  # noqa: E501

        :return: The ratings_provider of this MutableRatingProposal.
        :rtype: str
        """
        return self._ratings_provider

    @ratings_provider.setter
    def ratings_provider(self, ratings_provider: str):
        """Sets the ratings_provider of this MutableRatingProposal.

        Usually the NERC id of the entity.  # noqa: E501

        :param ratings_provider: The ratings_provider of this MutableRatingProposal.
        :type ratings_provider: str
        """
        if ratings_provider is not None and len(ratings_provider) > 10:
            raise ValueError("Invalid value for `ratings_provider`, length must be less than or equal to `10`")  # noqa: E501
        if ratings_provider is not None and not re.search(r'^[A-Z\-]{3,10}$', ratings_provider):  # noqa: E501
            raise ValueError("Invalid value for `ratings_provider`, must be a follow pattern or equal to `/^[A-Z\-]{3,10}$/`")  # noqa: E501

        self._ratings_provider = ratings_provider
