from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from trolie-flask.models.base_model import Model
import re
from trolie-flask import util

import re  # noqa: E501

class NetworkComponentName(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, scheme=None, name=None):  # noqa: E501
        """NetworkComponentName - a model defined in OpenAPI

        :param scheme: The scheme of this NetworkComponentName.  # noqa: E501
        :type scheme: str
        :param name: The name of this NetworkComponentName.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'scheme': str,
            'name': str
        }

        self.attribute_map = {
            'scheme': 'scheme',
            'name': 'name'
        }

        self._scheme = scheme
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'NetworkComponentName':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The network-component-name of this NetworkComponentName.  # noqa: E501
        :rtype: NetworkComponentName
        """
        return util.deserialize_model(dikt, cls)

    @property
    def scheme(self) -> str:
        """Gets the scheme of this NetworkComponentName.

         Contains a unique identifier for an object.    # noqa: E501

        :return: The scheme of this NetworkComponentName.
        :rtype: str
        """
        return self._scheme

    @scheme.setter
    def scheme(self, scheme: str):
        """Sets the scheme of this NetworkComponentName.

         Contains a unique identifier for an object.    # noqa: E501

        :param scheme: The scheme of this NetworkComponentName.
        :type scheme: str
        """
        if scheme is not None and len(scheme) > 250:
            raise ValueError("Invalid value for `scheme`, length must be less than or equal to `250`")  # noqa: E501
        if scheme is not None and not re.search(r'^(.){0,250}$', scheme):  # noqa: E501
            raise ValueError("Invalid value for `scheme`, must be a follow pattern or equal to `/^(.){0,250}$/`")  # noqa: E501

        self._scheme = scheme

    @property
    def name(self) -> str:
        """Gets the name of this NetworkComponentName.

         Contains a unique identifier for an object.    # noqa: E501

        :return: The name of this NetworkComponentName.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this NetworkComponentName.

         Contains a unique identifier for an object.    # noqa: E501

        :param name: The name of this NetworkComponentName.
        :type name: str
        """
        if name is not None and len(name) > 250:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `250`")  # noqa: E501
        if name is not None and not re.search(r'^(.){0,250}$', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^(.){0,250}$/`")  # noqa: E501

        self._name = name
