from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.common_header import CommonHeader
from openapi_server.models.seasonal_rating_snapshot_item import SeasonalRatingSnapshotItem
from openapi_server import util

from openapi_server.models.common_header import CommonHeader  # noqa: E501
from openapi_server.models.seasonal_rating_snapshot_item import SeasonalRatingSnapshotItem  # noqa: E501

class SeasonalRatingSnapshot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, snapshot_header=None, limits=None):  # noqa: E501
        """SeasonalRatingSnapshot - a model defined in OpenAPI

        :param snapshot_header: The snapshot_header of this SeasonalRatingSnapshot.  # noqa: E501
        :type snapshot_header: CommonHeader
        :param limits: The limits of this SeasonalRatingSnapshot.  # noqa: E501
        :type limits: List[SeasonalRatingSnapshotItem]
        """
        self.openapi_types = {
            'snapshot_header': CommonHeader,
            'limits': List[SeasonalRatingSnapshotItem]
        }

        self.attribute_map = {
            'snapshot_header': 'snapshot-header',
            'limits': 'limits'
        }

        self._snapshot_header = snapshot_header
        self._limits = limits

    @classmethod
    def from_dict(cls, dikt) -> 'SeasonalRatingSnapshot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The seasonal-rating-snapshot of this SeasonalRatingSnapshot.  # noqa: E501
        :rtype: SeasonalRatingSnapshot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def snapshot_header(self) -> CommonHeader:
        """Gets the snapshot_header of this SeasonalRatingSnapshot.


        :return: The snapshot_header of this SeasonalRatingSnapshot.
        :rtype: CommonHeader
        """
        return self._snapshot_header

    @snapshot_header.setter
    def snapshot_header(self, snapshot_header: CommonHeader):
        """Sets the snapshot_header of this SeasonalRatingSnapshot.


        :param snapshot_header: The snapshot_header of this SeasonalRatingSnapshot.
        :type snapshot_header: CommonHeader
        """

        self._snapshot_header = snapshot_header

    @property
    def limits(self) -> List[SeasonalRatingSnapshotItem]:
        """Gets the limits of this SeasonalRatingSnapshot.

        Seasonal rating snapshot  # noqa: E501

        :return: The limits of this SeasonalRatingSnapshot.
        :rtype: List[SeasonalRatingSnapshotItem]
        """
        return self._limits

    @limits.setter
    def limits(self, limits: List[SeasonalRatingSnapshotItem]):
        """Sets the limits of this SeasonalRatingSnapshot.

        Seasonal rating snapshot  # noqa: E501

        :param limits: The limits of this SeasonalRatingSnapshot.
        :type limits: List[SeasonalRatingSnapshotItem]
        """
        if limits is not None and len(limits) > 50000:
            raise ValueError("Invalid value for `limits`, number of items must be less than or equal to `50000`")  # noqa: E501
        if limits is not None and len(limits) < 0:
            raise ValueError("Invalid value for `limits`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._limits = limits
