from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from trolie-flask.models.base_model import Model
from trolie-flask.models.seasonal_proposals import SeasonalProposals
import re
from trolie-flask import util

from trolie-flask.models.seasonal_proposals import SeasonalProposals  # noqa: E501
import re  # noqa: E501

class SeasonalRatingProposal(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, last_updated=None, ratings_provider=None, ratings=None):  # noqa: E501
        """SeasonalRatingProposal - a model defined in OpenAPI

        :param last_updated: The last_updated of this SeasonalRatingProposal.  # noqa: E501
        :type last_updated: datetime
        :param ratings_provider: The ratings_provider of this SeasonalRatingProposal.  # noqa: E501
        :type ratings_provider: str
        :param ratings: The ratings of this SeasonalRatingProposal.  # noqa: E501
        :type ratings: List[SeasonalProposals]
        """
        self.openapi_types = {
            'last_updated': datetime,
            'ratings_provider': str,
            'ratings': List[SeasonalProposals]
        }

        self.attribute_map = {
            'last_updated': 'last-updated',
            'ratings_provider': 'ratings-provider',
            'ratings': 'ratings'
        }

        self._last_updated = last_updated
        self._ratings_provider = ratings_provider
        self._ratings = ratings

    @classmethod
    def from_dict(cls, dikt) -> 'SeasonalRatingProposal':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The seasonal-rating-proposal of this SeasonalRatingProposal.  # noqa: E501
        :rtype: SeasonalRatingProposal
        """
        return util.deserialize_model(dikt, cls)

    @property
    def last_updated(self) -> datetime:
        """Gets the last_updated of this SeasonalRatingProposal.

        RFC 3339 date-time string with a maximum of 10 digits in the fractional seconds component, i.e., nanosecond precision.  # noqa: E501

        :return: The last_updated of this SeasonalRatingProposal.
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated: datetime):
        """Sets the last_updated of this SeasonalRatingProposal.

        RFC 3339 date-time string with a maximum of 10 digits in the fractional seconds component, i.e., nanosecond precision.  # noqa: E501

        :param last_updated: The last_updated of this SeasonalRatingProposal.
        :type last_updated: datetime
        """
        if last_updated is not None and len(last_updated) > 35:
            raise ValueError("Invalid value for `last_updated`, length must be less than or equal to `35`")  # noqa: E501

        self._last_updated = last_updated

    @property
    def ratings_provider(self) -> str:
        """Gets the ratings_provider of this SeasonalRatingProposal.

        Usually the NERC id of the entity.  # noqa: E501

        :return: The ratings_provider of this SeasonalRatingProposal.
        :rtype: str
        """
        return self._ratings_provider

    @ratings_provider.setter
    def ratings_provider(self, ratings_provider: str):
        """Sets the ratings_provider of this SeasonalRatingProposal.

        Usually the NERC id of the entity.  # noqa: E501

        :param ratings_provider: The ratings_provider of this SeasonalRatingProposal.
        :type ratings_provider: str
        """
        if ratings_provider is not None and len(ratings_provider) > 10:
            raise ValueError("Invalid value for `ratings_provider`, length must be less than or equal to `10`")  # noqa: E501
        if ratings_provider is not None and not re.search(r'^[A-Z\-]{3,10}$', ratings_provider):  # noqa: E501
            raise ValueError("Invalid value for `ratings_provider`, must be a follow pattern or equal to `/^[A-Z\-]{3,10}$/`")  # noqa: E501

        self._ratings_provider = ratings_provider

    @property
    def ratings(self) -> List[SeasonalProposals]:
        """Gets the ratings of this SeasonalRatingProposal.

        Set of forecast limits  # noqa: E501

        :return: The ratings of this SeasonalRatingProposal.
        :rtype: List[SeasonalProposals]
        """
        return self._ratings

    @ratings.setter
    def ratings(self, ratings: List[SeasonalProposals]):
        """Sets the ratings of this SeasonalRatingProposal.

        Set of forecast limits  # noqa: E501

        :param ratings: The ratings of this SeasonalRatingProposal.
        :type ratings: List[SeasonalProposals]
        """
        if ratings is not None and len(ratings) > 50000:
            raise ValueError("Invalid value for `ratings`, number of items must be less than or equal to `50000`")  # noqa: E501
        if ratings is not None and len(ratings) < 0:
            raise ValueError("Invalid value for `ratings`, number of items must be greater than or equal to `0`")  # noqa: E501

        self._ratings = ratings
