from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from trolie-flask.models.base_model import Model
from trolie-flask import util


class UndervoltageThreshold(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, k_v_min=None):  # noqa: E501
        """UndervoltageThreshold - a model defined in OpenAPI

        :param k_v_min: The k_v_min of this UndervoltageThreshold.  # noqa: E501
        :type k_v_min: float
        """
        self.openapi_types = {
            'k_v_min': float
        }

        self.attribute_map = {
            'k_v_min': 'kV-min'
        }

        self._k_v_min = k_v_min

    @classmethod
    def from_dict(cls, dikt) -> 'UndervoltageThreshold':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The undervoltage-threshold of this UndervoltageThreshold.  # noqa: E501
        :rtype: UndervoltageThreshold
        """
        return util.deserialize_model(dikt, cls)

    @property
    def k_v_min(self) -> float:
        """Gets the k_v_min of this UndervoltageThreshold.


        :return: The k_v_min of this UndervoltageThreshold.
        :rtype: float
        """
        return self._k_v_min

    @k_v_min.setter
    def k_v_min(self, k_v_min: float):
        """Sets the k_v_min of this UndervoltageThreshold.


        :param k_v_min: The k_v_min of this UndervoltageThreshold.
        :type k_v_min: float
        """
        if k_v_min is None:
            raise ValueError("Invalid value for `k_v_min`, must not be `None`")  # noqa: E501
        if k_v_min is not None and k_v_min > 1100:  # noqa: E501
            raise ValueError("Invalid value for `k_v_min`, must be a value less than or equal to `1100`")  # noqa: E501
        if k_v_min is not None and k_v_min < 0:  # noqa: E501
            raise ValueError("Invalid value for `k_v_min`, must be a value greater than or equal to `0`")  # noqa: E501

        self._k_v_min = k_v_min
